default:
  navigation:
    - title: Mujer
      subtitle: Categorías
      url: /t/mujer
      items:
        - :title: Anillos
          :url: /t/mujer/anillos
        - :title: Collares
          :url: /t/mujer/collares
        - :title: Aretes
          :url: /t/mujer/aretes
        - :title: Pulseras
          :url: /t/mujer/pulseras
        - :title: Sets
          :url: /t/mujer/sets
        - :title: Tobilleras
          :url: /t/mujer/tobilleras
      promo_banners:
        - subtitle: New collection
          title: Summer 2020
          url: /t/new-collection/summer-2020
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Accesorios
      subtitle: Categorías
      url: /t/mujer
      items:
        - :title: Anillos
          :url: /t/mujer/anillos
        - :title: Collares
          :url: /t/mujer/collares
        - :title: Aretes
          :url: /t/mujer/aretes
        - :title: Pulseras
          :url: /t/mujer/pulseras
        - :title: Sets
          :url: /t/mujer/sets
        - :title: Tobilleras
          :url: /t/mujer/tobilleras
      promo_banners:
        - subtitle: New collection
          title: Summer 2020
          url: /t/new-collection/summer-2020
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    # - title: Men
    #   subtitle: Categorías
    #   url: /t/men
    #   items:
    #     - :title: Relojes
    #       :url: /t/men/relojes
    #     - :title: T-shirts
    #       :url: /t/men/t-shirts
    #     - :title: Sweaters
    #       :url: /t/men/sweaters
    #     - :title: Jackets and Coats
    #       :url: /t/men/jackets-and-coats
    #   promo_banners:
    #     - subtitle: New collection
    #       title: Summer 2019
    #       url: /t/new-collection/summer-2019
    #       image: 'meganav/promo_banner_left-second-category.jpg'
    #     - subtitle: Special Offers
    #       title: Get up to 30% off
    #       url: /t/special-offers/30-off
    #       image: 'meganav/promo_banner_right-second-category.jpg'